// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn5Yj9pM6pBTLh2vLbtbh5yc0n_P03mf4',
    appId: '1:535987886392:web:77f619e3a8df868b2389cd',
    messagingSenderId: '535987886392',
    projectId: 'chatacter',
    authDomain: 'chatacter.firebaseapp.com',
    storageBucket: 'chatacter.appspot.com',
    measurementId: 'G-GFDEHRZ2B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjIpVJBPpYSaYexe0UUs5BZasvg4mIzws',
    appId: '1:535987886392:android:177a2bf02105e0642389cd',
    messagingSenderId: '535987886392',
    projectId: 'chatacter',
    storageBucket: 'chatacter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLm9VzBZrVR4pTYtr61rIRu9HgKsCjuQY',
    appId: '1:535987886392:ios:d25094a39f8aa8862389cd',
    messagingSenderId: '535987886392',
    projectId: 'chatacter',
    storageBucket: 'chatacter.appspot.com',
    iosBundleId: 'com.alphasphere.chatacter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLm9VzBZrVR4pTYtr61rIRu9HgKsCjuQY',
    appId: '1:535987886392:ios:15d15aad4317da292389cd',
    messagingSenderId: '535987886392',
    projectId: 'chatacter',
    storageBucket: 'chatacter.appspot.com',
    iosBundleId: 'com.example.chatacter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn5Yj9pM6pBTLh2vLbtbh5yc0n_P03mf4',
    appId: '1:535987886392:web:b6dcb20b267280062389cd',
    messagingSenderId: '535987886392',
    projectId: 'chatacter',
    authDomain: 'chatacter.firebaseapp.com',
    storageBucket: 'chatacter.appspot.com',
    measurementId: 'G-YSFVTVHBDF',
  );
}
